language: php

os: linux
dist: xenial

php:
  - 7.4
  - 8.0

cache:
  timeout: 3
  directories:
    - $HOME/.cache

install: travis_retry composer install --no-suggest --optimize-autoloader --no-progress --no-interaction

script: vendor/bin/phpunit --verbose
